<a href="https://colab.research.google.com/github/ymohd022/Dl/blob/main/Copy_of_DL4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Statistical Operations
rows = int(input("Enter number of rows: "))
cols = int(input("Enter number of columns: "))

tensor = np.empty((rows, cols))

for i in range(rows):
    for j in range(cols):
        tensor[i][j] = float(input(f"Enter value for [{i}][{j}]: "))

print("\nTensor: \n", tensor)

# Statistical calculations
mean = np.mean(tensor)
std = np.std(tensor)
var = np.var(tensor)
max_val = np.max(tensor)
min_val = np.min(tensor)

print("\nStatistics:")
print("Mean:", mean)
print("Standard Deviation:", std)
print("Variance:", var)
print("Maximum value:", max_val)
print("Minimum value:", min_val)

# Reshape and Transpose
reshaped_tensor = np.reshape(tensor, (-1, 1))
transposed_tensor = np.transpose(tensor)

print("\nReshaped tensor: \n", reshaped_tensor)
print("Transposed tensor: \n", transposed_tensor)

# Dot product of tensor and its transpose
dot_product = np.dot(tensor, transposed_tensor)
print("Dot product: \n", dot_product)

# Split and Merge Operations
rows = int(input("Enter number of rows for split/merge tensor: "))
cols = int(input("Enter number of columns for split/merge tensor: "))

tensor = np.empty((rows, cols))

for i in range(rows):
    for j in range(cols):
        tensor[i][j] = float(input(f"Enter value for [{i}][{j}]: "))

print("\nOriginal tensor: \n", tensor)

# Axis selection and splitting
split_axis = int(input("Enter the axis to split along (0 for rows, 1 for columns): "))

if split_axis not in [0, 1]:
    print("Invalid axis! Defaulting to axis 0.")
    split_axis = 0

# Ensure the tensor can be split evenly
if (split_axis == 0 and rows % 2 != 0) or (split_axis == 1 and cols % 2 != 0):
    print("Cannot split tensor evenly along the chosen axis.")
else:
    tensor_split = np.split(tensor, 2, axis=split_axis)
    print("Split tensors: \n", tensor_split)

    # Merge tensors
    tensor_merged = np.concatenate(tensor_split, axis=split_axis)
    print("Merged tensor: \n", tensor_merged)

Enter number of rows: 2
Enter number of columns: 2
Enter value for [0][0]: 1
Enter value for [0][1]: 2
Enter value for [1][0]: 3
Enter value for [1][1]: 4

Tensor: 
 [[1. 2.]
 [3. 4.]]

Statistics:
Mean: 2.5
Standard Deviation: 1.118033988749895
Variance: 1.25
Maximum value: 4.0
Minimum value: 1.0

Reshaped tensor: 
 [[1.]
 [2.]
 [3.]
 [4.]]
Transposed tensor: 
 [[1. 3.]
 [2. 4.]]
Dot product: 
 [[ 5. 11.]
 [11. 25.]]
Enter number of rows for split/merge tensor: 2
Enter number of columns for split/merge tensor: 2
Enter value for [0][0]: 1
Enter value for [0][1]: 2
Enter value for [1][0]: 3
Enter value for [1][1]: 4

Original tensor: 
 [[1. 2.]
 [3. 4.]]
Enter the axis to split along (0 for rows, 1 for columns): 0
Split tensors: 
 [array([[1., 2.]]), array([[3., 4.]])]
Merged tensor: 
 [[1. 2.]
 [3. 4.]]


In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import SGD, Adam, RMSprop
from tensorflow.keras.activations import relu, sigmoid, tanh

# Loading the data of breast cancer from sklearn
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

data = load_breast_cancer()

x_train, x_test, y_train, y_test = train_test_split(data.data, data.target, test_size=0.2, random_state=42)
# Model creation function
def create_model(activation_func, optimizer):
    model = Sequential([
        Dense(64, input_dim=x_train.shape[1], activation=activation_func),
        Dropout(0.5),
        Dense(32, activation=activation_func),
        Dropout(0.5),
        Dense(1, activation='sigmoid')
    ])

    model.compile(optimizer=optimizer, loss='binary_crossentropy', metrics=['accuracy'])

    return model

# Define the activation functions and optimizers to try
activation_functions = [relu, sigmoid, tanh]
optimizer_classes = [SGD, Adam, RMSprop]

# Train and test the models with different activation functions and optimizers
for activation_func in activation_functions:
    for optimizer_class in optimizer_classes:
        optimizer = optimizer_class(learning_rate=0.001)  # Create a new optimizer instance in each iteration

        model = create_model(activation_func, optimizer)
        print(f"Training model with activation function {activation_func.__name__} and optimizer {optimizer_class.__name__}")

        model.fit(x_train, y_train, epochs=50, batch_size=16, verbose=0)
        loss, accuracy = model.evaluate(x_test, y_test, verbose=0)

        print(f"Test loss: {loss:.3f}, Test accuracy: {accuracy:.3f}")

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Training model with activation function relu and optimizer SGD
Test loss: 0.495, Test accuracy: 0.939
Training model with activation function relu and optimizer Adam
Test loss: 0.335, Test accuracy: 0.930
Training model with activation function relu and optimizer RMSprop
Test loss: 0.190, Test accuracy: 0.947
Training model with activation function sigmoid and optimizer SGD
Test loss: 0.615, Test accuracy: 0.623
Training model with activation function sigmoid and optimizer Adam
Test loss: 0.211, Test accuracy: 0.947
Training model with activation function sigmoid and optimizer RMSprop
Test loss: 0.191, Test accuracy: 0.930
Training model with activation function tanh and optimizer SGD
Test loss: 0.686, Test accuracy: 0.623
Training model with activation function tanh and optimizer Adam
Test loss: 0.202, Test accuracy: 0.921
Training model with activation function tanh and optimizer RMSprop
Test loss: 0.139, Test accuracy: 0.939


In [ ]:
import tensorflow as tf
from tensorflow.keras import layers, models, optimizers
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import EarlyStopping
# Set the parameters
batch_size = 32
image_height = 128
image_width = 128
num_classes = 3
num_epochs = 50
# Create the LeNet model
def build_lenet_model():
 model = models.Sequential()
 model.add(layers.Conv2D(32, (5, 5), activation='relu', input_shape=(image_height,
image_width, 3)))
 model.add(layers.MaxPooling2D((2, 2)))
 model.add(layers.Conv2D(64, (5, 5), activation='relu'))
 model.add(layers.MaxPooling2D((2, 2)))
 model.add(layers.Flatten())
 model.add(layers.Dense(64, activation='relu'))
 model.add(layers.Dense(num_classes, activation='softmax'))
 return model
# Create the AlexNet model
def build_alexnet_model():
 model = models.Sequential()
 model.add(layers.Conv2D(96, (11, 11), strides=(4, 4), activation='relu',
input_shape=(image_height, image_width, 3)))
 model.add(layers.MaxPooling2D((3, 3), strides=(2, 2)))
 model.add(layers.Conv2D(256, (5, 5), activation='relu', padding="same"))
 model.add(layers.MaxPooling2D((3, 3), strides=(2, 2)))
 model.add(layers.Conv2D(384, (3, 3), activation='relu', padding="same"))
 model.add(layers.Conv2D(384, (3, 3), activation='relu', padding="same"))
 model.add(layers.Conv2D(256, (3, 3), activation='relu', padding="same"))
 model.add(layers.MaxPooling2D((3, 3), strides=(2, 2)))
 model.add(layers.Flatten())
 model.add(layers.Dense(4096, activation='relu'))
 model.add(layers.Dense(4096, activation='relu'))
 model.add(layers.Dense(num_classes, activation='softmax'))
 return model
# Create the VGG model
def build_vgg_model():
 model = models.Sequential()
 model.add(layers.Conv2D(64, (3, 3), activation='relu', padding='same',
input_shape=(image_height, image_width, 3)))
 model.add(layers.Conv2D(64, (3, 3), activation='relu', padding='same'))
 model.add(layers.MaxPooling2D((2, 2), strides=(2, 2)))
 model.add(layers.Conv2D(128, (3, 3), activation='relu', padding='same'))
 model.add(layers.Conv2D(128, (3, 3), activation='relu', padding='same'))
 model.add(layers.MaxPooling2D((2, 2), strides=(2, 2)))
 model.add(layers.Conv2D(256, (3, 3), activation='relu', padding='same'))
 model.add(layers.Conv2D(256, (3, 3), activation='relu', padding='same'))
 model.add(layers.Conv2D(256, (3, 3), activation='relu', padding='same'))
 model.add(layers.MaxPooling2D((2, 2), strides=(2, 2)))
 model.add(layers.Conv2D(512, (3, 3), activation='relu', padding='same'))
 model.add(layers.Conv2D(512, (3, 3), activation='relu', padding='same'))
 model.add(layers.Conv2D(512, (3, 3), activation='relu', padding='same'))
 model.add(layers.MaxPooling2D((2, 2), strides=(2, 2)))
 model.add(layers.Conv2D(512, (3, 3), activation='relu', padding='same'))
 model.add(layers.Conv2D(512, (3, 3), activation='relu', padding='same'))
 model.add(layers.Conv2D(512, (3, 3), activation='relu', padding='same'))
 model.add(layers.MaxPooling2D((2, 2), strides=(2, 2)))
 model.add(layers.Flatten())
 model.add(layers.Dense(4096, activation='relu'))
 model.add(layers.Dense(4096, activation='relu'))
 model.add(layers.Dense(num_classes, activation='softmax'))
 return model
# Select the model architecture
model = build_vgg_model() # Change the function name to choose a different
# Compile the model
model.compile(optimizer='adam',
 loss=tf.keras.losses.CategoricalCrossentropy(from_logits=True),
 metrics=['accuracy'])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
# Load and preprocess the image data
train_datagen = ImageDataGenerator(rescale=1./255, validation_split=0.2)
train_data_dir = 'path/to/training/directory'
train_generator = train_datagen.flow_from_directory(
 train_data_dir,
 target_size=(image_height, image_width),
 batch_size=batch_size,
 class_mode='categorical',
 subset='training'
)
validation_generator = train_datagen.flow_from_directory(
 train_data_dir,
 target_size=(image_height, image_width),
 batch_size=batch_size,
 class_mode='categorical',
 subset='validation'
)
# Apply data augmentation to avoid overfitting
train_datagen_augmented = ImageDataGenerator(
 rescale=1./255,
 rotation_range=20,
 width_shift_range=0.2,
 height_shift_range=0.2,
 shear_range=0.2,
 zoom_range=0.2,
 horizontal_flip=True,
 fill_mode='nearest'
)
train_generator_augmented = train_datagen_augmented.flow_from_directory(
 train_data_dir,
 target_size=(image_height, image_width),
 batch_size=batch_size,
 class_mode='categorical',
 subset='training'
)
# Early stopping to avoid overfitting
early_stopping = EarlyStopping(monitor='val_loss', patience=5)
# Train the model
history = model.fit(
 train_generator_augmented,
 validation_data=validation_generator,
 epochs=num_epochs,
 callbacks=[early_stopping]
)
# Evaluate the model
test_data_dir = 'path/to/test/directory'
test_datagen = ImageDataGenerator(rescale=1./255)
test_generator = test_datagen.flow_from_directory(
 test_data_dir,
 target_size=(image_height, image_width),
 batch_size=batch_size,
 class_mode='categorical'
)
accuracy = model.evaluate(test_generator)
print("Test accuracy:", accuracy[1])
# Check for overfitting or underfitting
import matplotlib.pyplot as plt
train_loss = history.history['loss']
val_loss = history.history['val_loss']
train_acc = history.history['accuracy']
val_acc = history.history['val_accuracy']
epochs_range = range(len(train_loss))
plt.figure(figsize=(12, 4))
plt.subplot(1, 2, 1)
plt.plot(epochs_range, train_loss, label='Training Loss')
plt.plot(epochs_range, val_loss, label='Validation Loss')
plt.legend(loc='upper right')
plt.title('Training and Validation Loss')
plt.subplot(1, 2, 2)
plt.plot(epochs_range, train_acc, label='Training Accuracy')
plt.plot(epochs_range, val_acc, label='Validation Accuracy')
plt.legend(loc='lower right')
plt.title('Training and Validation Accuracy')
plt.show()


FileNotFoundError: [Errno 2] No such file or directory: 'path/to/training/directory'